In [20]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

from sklearn.metrics import confusion_matrix

In [2]:
# Load the cleaned loan dataset created in Part B1

df = pd.read_csv("clean_loan_dataset.csv")

print("=" * 60)
print("STEP 1: LOAD DATASET")
print("=" * 60)

print(df.head())

print("\nDataset Shape:")
print(df.shape)

STEP 1: LOAD DATASET
     Income  CreditScore  EmploymentYears  LoanAmount  HasCollateral  \
0  0.585174     0.121560         0.024490    0.339800            1.0   
1  0.498215     0.091743         0.591837    0.101287            1.0   
2  0.018530     0.353211         0.200000    0.115989            0.0   
3  0.000000     0.176606         0.697959    0.032673            1.0   
4  0.088490     0.098624         0.379592    0.093118            0.0   

   PreviousDefaults  Approved  DebtToIncome  IncomePerYearEmployed  
0               0.0         0      0.258296               0.846035  
1               0.0         1      0.104832               0.082051  
2               0.0         1      0.496387               0.055679  
3               0.0         1      0.300982               0.004620  
4               0.0         1      0.310994               0.040752  

Dataset Shape:
(100, 9)


In [3]:
# Separate the target variable (Approved) from the feature variables

X = df.drop(columns=["Approved"])
y = df["Approved"]

print("=" * 60)
print("STEP 2: PREPARE FEATURES & TARGET")
print("=" * 60)

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nFeature Columns:")
print(X.columns.tolist())

STEP 2: PREPARE FEATURES & TARGET
Features Shape: (100, 8)
Target Shape: (100,)

Feature Columns:
['Income', 'CreditScore', 'EmploymentYears', 'LoanAmount', 'HasCollateral', 'PreviousDefaults', 'DebtToIncome', 'IncomePerYearEmployed']


In [4]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("=" * 60)
print("STEP 3: TRAIN TEST SPLIT")
print("=" * 60)

print("Training Set:", X_train.shape)
print("Testing Set :", X_test.shape)

STEP 3: TRAIN TEST SPLIT
Training Set: (80, 8)
Testing Set : (20, 8)


In [7]:
# Train the Logistic Regression model

log_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_model.fit(X_train, y_train)

print("=" * 60)
print("STEP 4: LOGISTIC REGRESSION")
print("=" * 60)

print("Logistic Regression model trained successfully.")

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [8]:
print(X_train.isnull().sum())
print("\nTotal NaNs:", X_train.isnull().sum().sum())

Income                   0
CreditScore              0
EmploymentYears          0
LoanAmount               0
HasCollateral            1
PreviousDefaults         2
DebtToIncome             0
IncomePerYearEmployed    0
dtype: int64

Total NaNs: 3


In [9]:
X_train = X_train.fillna(X_train.median(numeric_only=True))
X_test = X_test.fillna(X_test.median(numeric_only=True))

In [10]:
binary_cols = ["HasCollateral", "PreviousDefaults"]

for col in binary_cols:
    X_train[col] = X_train[col].fillna(X_train[col].mode()[0])
    X_test[col] = X_test[col].fillna(X_test[col].mode()[0])

In [11]:
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)

print("Logistic Regression trained successfully")

Logistic Regression trained successfully


In [13]:
 # Function to evaluate classification models

def evaluate_model(name, model):
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    print("=" * 60)
    print(f"{name} Performance")
    print("=" * 60)
    
    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1-Score :", f1_score(y_test, y_pred))
    
    return y_pred

In [14]:
log_pred = evaluate_model("Logistic Regression", log_model)
rf_pred = evaluate_model("Random Forest", rf_model)
dt_pred = evaluate_model("Decision Tree", dt_model)

Logistic Regression Performance
Accuracy : 0.7
Precision: 0.7058823529411765
Recall   : 0.9230769230769231
F1-Score : 0.8


NameError: name 'rf_model' is not defined

In [15]:
print(rf_model)

NameError: name 'rf_model' is not defined

In [16]:
# Train Random Forest model again

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Random Forest trained successfully")

Random Forest trained successfully


In [17]:
log_pred = evaluate_model("Logistic Regression", log_model)
rf_pred = evaluate_model("Random Forest", rf_model)
dt_pred = evaluate_model("Decision Tree", dt_model)

Logistic Regression Performance
Accuracy : 0.7
Precision: 0.7058823529411765
Recall   : 0.9230769230769231
F1-Score : 0.8
Random Forest Performance
Accuracy : 0.65
Precision: 0.7142857142857143
Recall   : 0.7692307692307693
F1-Score : 0.7407407407407407


NameError: name 'dt_model' is not defined

In [18]:
# Train Decision Tree model

dt_model = DecisionTreeClassifier(
    random_state=42
)

dt_model.fit(X_train, y_train)

print("Decision Tree trained successfully")

Decision Tree trained successfully


In [19]:
log_pred = evaluate_model("Logistic Regression", log_model)
rf_pred = evaluate_model("Random Forest", rf_model)
dt_pred = evaluate_model("Decision Tree", dt_model)

Logistic Regression Performance
Accuracy : 0.7
Precision: 0.7058823529411765
Recall   : 0.9230769230769231
F1-Score : 0.8
Random Forest Performance
Accuracy : 0.65
Precision: 0.7142857142857143
Recall   : 0.7692307692307693
F1-Score : 0.7407407407407407
Decision Tree Performance
Accuracy : 0.7
Precision: 0.7058823529411765
Recall   : 0.9230769230769231
F1-Score : 0.8


In [21]:
# Function to display confusion matrix

def show_confusion_matrix(name, model):
    
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    
    print("=" * 60)
    print(f"{name} Confusion Matrix")
    print("=" * 60)
    
    print(cm)

In [22]:
show_confusion_matrix("Logistic Regression", log_model)
show_confusion_matrix("Random Forest", rf_model)
show_confusion_matrix("Decision Tree", dt_model)

Logistic Regression Confusion Matrix
[[ 2  5]
 [ 1 12]]
Random Forest Confusion Matrix
[[ 3  4]
 [ 3 10]]
Decision Tree Confusion Matrix
[[ 2  5]
 [ 1 12]]


In [23]:
i = 0  # you can change index

sample = X_test.iloc[[i]]

print("=" * 60)
print("SANITY CHECK")
print("=" * 60)

print("Actual Label:", y_test.iloc[i])

print("Logistic Regression Prediction:", log_model.predict(sample)[0])
print("Random Forest Prediction:", rf_model.predict(sample)[0])
print("Decision Tree Prediction:", dt_model.predict(sample)[0])

SANITY CHECK
Actual Label: 1
Logistic Regression Prediction: 0
Random Forest Prediction: 0
Decision Tree Prediction: 1
